/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package analex;

import java.awt.Color;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JPanel;

/**
 *
 * @author luisa
 * 
 */
public class Cover extends javax.swing.JFrame {

    /**
     * Creates new form Cover
     */
    public Cover() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        anio = new javax.swing.JComboBox<>();
        tChamp = new javax.swing.JTextField();
        Limpiar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        tVez = new javax.swing.JTextField();
        jFotoChamp = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jFotoTercer = new javax.swing.JLabel();
        jFotoSegundo = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        tSegundo = new javax.swing.JTextField();
        tTercer = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(51, 0, 51));

        jLabel1.setFont(new java.awt.Font("Arial Narrow", 1, 15)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Campeones de la Premier League");

        jLabel2.setFont(new java.awt.Font("Arial Narrow", 1, 15)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Introduzca la temporada:");

        anio.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1992-1993", "1993-1994", "1994-1995", "1995-1996", "1996-1997", "1997-1998", "1998-1999", "1999-2000", "2000-2001", "2001-2002", "2002-2003", "2003-2004", "2004-2005", "2005-2006", "2006-2007", "2007-2008", "2008-2009", "2009-2010", "2010-2011", "2011-2012", "2012-2013", "2013-2014", "2014-2015", "2015-2016", "2016-2017", "2017-2018", "2018-2019", "2019-2020" }));
        anio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                anioActionPerformed(evt);
            }
        });

        Limpiar.setText("Limpiar");
        Limpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LimpiarActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Arial Narrow", 1, 15)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("El club campeón fue: ");

        jFotoChamp.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jLabel5.setIcon(new javax.swing.ImageIcon("C:\\Users\\luisa\\Documents\\NetBeansProjects\\analex\\PLVec (1).png")); // NOI18N

        jLabel6.setFont(new java.awt.Font("Arial Narrow", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Desde la temporada 1992-1993");

        jFotoTercer.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jFotoSegundo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jLabel9.setFont(new java.awt.Font("Arial Narrow", 1, 15)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Tercer Lugar:");

        jLabel10.setFont(new java.awt.Font("Arial Narrow", 1, 15)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Segundo Lugar:");

        jLabel11.setFont(new java.awt.Font("Arial Narrow", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Campeón");

        jLabel12.setFont(new java.awt.Font("Arial Narrow", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("Segundo Lugar");

        jLabel13.setFont(new java.awt.Font("Arial Narrow", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("Tercer Lugar");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tChamp))
                    .addComponent(tVez)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(55, 55, 55)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 423, Short.MAX_VALUE)
                                .addGap(11, 11, 11))
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(anio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Limpiar)
                                .addGap(33, 33, 33))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tTercer))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tSegundo))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jFotoChamp, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jFotoSegundo, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE))
                        .addGap(28, 28, 28)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jFotoTercer, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
                            .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(anio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Limpiar)))
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tChamp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tVez, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(tSegundo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(tTercer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(jLabel13)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel11)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jFotoSegundo, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFotoChamp, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFotoTercer, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(33, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    /*
    private void iniciarComponentes(){
        JPanel panel = new JPanel();
        panel.setBackground(Color.yellow);
        this.getContentPane().add(panel);
    }
    */
    private void anioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_anioActionPerformed
        // TODO add your handling code here:
        //iniciarComponentes();
        String aniocamp = (String)anio.getSelectedItem();
        jFotoChamp.setVisible(true);
        jFotoSegundo.setVisible(true);
        jFotoTercer.setVisible(true);
        switch (aniocamp){
            case "1992-1993":
                tChamp.setText("Manchester United");
                tVez.setText("por primera vez en este formato");
                jFotoChamp.setIcon(new ImageIcon("ManUOld.png"));
                
                tSegundo.setText("Aston Villa F.C.");
                jFotoSegundo.setIcon(new ImageIcon("AstonVilla.png"));
                
                tTercer.setText("Norwich City");
                jFotoTercer.setIcon(new ImageIcon("Norwich.png"));
                break;
            case "1993-1994":
                tChamp.setText("Manchester United");
                tVez.setText("por segunda vez en este formato y segunda de forma consecutiva");
                jFotoChamp.setIcon(new ImageIcon("ManUOld.png"));
                
                tSegundo.setText("Blackburn Rovers F. C.");
                jFotoSegundo.setIcon(new ImageIcon("BRFC.png"));
                
                tTercer.setText("Newcastle United F.C.");
                jFotoTercer.setIcon(new ImageIcon("Newcastle.png"));
                break;
            case "1994-1995":
                tChamp.setText("Blackburn Rovers F. C.");
                tVez.setText("por primera vez en este formato");
                jFotoChamp.setIcon(new ImageIcon("BRFC.png"));
                
                tSegundo.setText("Manchester United");
                jFotoSegundo.setIcon(new ImageIcon("ManUOld.png"));
                
                tTercer.setText("Nottingham Forest F. C. ");
                jFotoTercer.setIcon(new ImageIcon("NFFC.png"));
                break;
            case "1995-1996":
                tChamp.setText("Manchester United");
                tVez.setText("por tercera vez en este formato");
                jFotoChamp.setIcon(new ImageIcon("ManUOld.png"));
                
                tSegundo.setText("Newcastle United F.C.");
                jFotoSegundo.setIcon(new ImageIcon("Newcastle.png"));
                
                tTercer.setText("Liverpool F.C.");
                jFotoTercer.setIcon(new ImageIcon("LFC.png"));
                break;
            case "1996-1997":
                tChamp.setText("Manchester United");
                tVez.setText("por cuarta vez en este formato y segunda de forma consecutiva");
                jFotoChamp.setIcon(new ImageIcon("ManUOld.png"));
                
                tSegundo.setText("Newcastle United F.C.");
                jFotoSegundo.setIcon(new ImageIcon("Newcastle.png"));
                
                tTercer.setText("Arsenal F.C.");
                jFotoTercer.setIcon(new ImageIcon("ArsenalOld.png"));
                break;
            case "1997-1998":
                tChamp.setText("Arsenal F.C.");
                tVez.setText("por primera vez en este formato");
                jFotoChamp.setIcon(new ImageIcon("ArsenalOld.png"));
                
                tSegundo.setText("Manchester United");
                jFotoSegundo.setIcon(new ImageIcon("ManUOld.png"));
                
                tTercer.setText("Liverpool F.C.");
                jFotoTercer.setIcon(new ImageIcon("LFC.png"));
                break;
            case "1998-1999":
                tChamp.setText("Manchester United");
                tVez.setText("por quinta vez en este formato");
                jFotoChamp.setIcon(new ImageIcon("ManU.png"));
                
                tSegundo.setText("Arsenal F.C.");
                jFotoSegundo.setIcon(new ImageIcon("ArsenalOld.png"));
                
                tTercer.setText("Chelsea F.C.");
                jFotoTercer.setIcon(new ImageIcon("ChelseaOld.png"));
                break;
            case "1999-2000":
                tChamp.setText("Manchester United");
                tVez.setText("por sexta vez en este formato y segunda de forma consecutiva");
                jFotoChamp.setIcon(new ImageIcon("ManU.png"));
                
                tSegundo.setText("Arsenal F.C.");
                jFotoSegundo.setIcon(new ImageIcon("ArsenalOld.png"));
                
                tTercer.setText("Leeds United F.C.");
                jFotoTercer.setIcon(new ImageIcon("Leeds.png"));
                break;
            case "2000-2001":
                tChamp.setText("Manchester United");
                tVez.setText("por séptima vez en este formato y tercera de forma consecutiva");
                jFotoChamp.setIcon(new ImageIcon("ManU.png"));
                
                tSegundo.setText("Arsenal F.C.");
                jFotoSegundo.setIcon(new ImageIcon("ArsenalOld.png"));
                
                tTercer.setText("Liverpool F.C.");
                jFotoTercer.setIcon(new ImageIcon("LFC.png"));
                break;
            case "2001-2002":
                tChamp.setText("Arsenal F.C.");
                tVez.setText("por segunda vez en este formato");
                jFotoChamp.setIcon(new ImageIcon("ArsenalOld.png"));
                
                tSegundo.setText("Liverpool F.C.");
                jFotoSegundo.setIcon(new ImageIcon("LFC.png"));
                
                tTercer.setText("Manchester United");
                jFotoTercer.setIcon(new ImageIcon("ManU.png"));
                break;
            case "2002-2003":
                tChamp.setText("Manchester United");
                tVez.setText("por octava vez en este formato");
                jFotoChamp.setIcon(new ImageIcon("ManU.png"));
                
                tSegundo.setText("Arsenal F.C.");
                jFotoSegundo.setIcon(new ImageIcon("ArsenalNew.png"));
                
                tTercer.setText("Newcastle United F.C.");
                jFotoTercer.setIcon(new ImageIcon("Newcastle.png"));
                break;
            case "2003-2004":
                tChamp.setText("Arsenal F.C.");
                tVez.setText("por tercera vez en este formato, siendo único campeón invicto");
                jFotoChamp.setIcon(new ImageIcon("ArsenalNew.png"));
                
                tSegundo.setText("Chelsea F.C.");
                jFotoSegundo.setIcon(new ImageIcon("ChelseaOld.png"));
                
                tTercer.setText("Manchester United");
                jFotoTercer.setIcon(new ImageIcon("ManU.png"));
                break;
            case "2004-2005":
                tChamp.setText("Chelsea F.C.");
                tVez.setText("por primera vez en este formato");
                jFotoChamp.setIcon(new ImageIcon("ChelseaOld.png"));
                
                tSegundo.setText("Arsenal F.C.");
                jFotoSegundo.setIcon(new ImageIcon("ArsenalNew.png"));
                
                tTercer.setText("Manchester United");
                jFotoTercer.setIcon(new ImageIcon("ManU.png"));
                break;
            case "2005-2006":
                tChamp.setText("Chelsea F.C.");
                tVez.setText("por segunda vez en este formato");
                jFotoChamp.setIcon(new ImageIcon("ChelseaNew.png"));
                
                tSegundo.setText("Manchester United");
                jFotoSegundo.setIcon(new ImageIcon("ManU.png"));
                
                tTercer.setText("Liverpool F.C.");
                jFotoTercer.setIcon(new ImageIcon("LFC.png"));
                break;
            case "2006-2007":
                tChamp.setText("Manchester United");
                tVez.setText("por novena vez en este formato");
                jFotoChamp.setIcon(new ImageIcon("ManU.png"));
                
                tSegundo.setText("Chelsea F.C.");
                jFotoSegundo.setIcon(new ImageIcon("ChelseaNew.png"));
                
                tTercer.setText("Liverpool F.C.");
                jFotoTercer.setIcon(new ImageIcon("LFC.png"));
                break;
            case "2007-2008":
                tChamp.setText("Manchester United");
                tVez.setText("por décima vez en este formato y segunda de forma consecutiva");
                jFotoChamp.setIcon(new ImageIcon("ManU.png"));
                
                tSegundo.setText("Chelsea F.C.");
                jFotoSegundo.setIcon(new ImageIcon("ChelseaNew.png"));
                
                tTercer.setText("Arsenal F.C.");
                jFotoTercer.setIcon(new ImageIcon("ArsenalNew.png"));
                break;
            case "2008-2009":
                tChamp.setText("Manchester United");
                tVez.setText("por undécima vez en este formato y tercera de forma consecutiva");
                jFotoChamp.setIcon(new ImageIcon("ManU.png"));
                
                tSegundo.setText("Liverpool F.C.");
                jFotoSegundo.setIcon(new ImageIcon("LFC.png"));
                
                tTercer.setText("Chelsea F.C.");
                jFotoTercer.setIcon(new ImageIcon("ChelseaNew.png"));
                break;
            case "2009-2010":
                tChamp.setText("Chelsea F.C.");
                tVez.setText("por tercera vez en este formato");
                jFotoChamp.setIcon(new ImageIcon("ChelseaNew.png"));
                
                tSegundo.setText("Manchester United");
                jFotoSegundo.setIcon(new ImageIcon("ManU.png"));
                
                tTercer.setText("Arsenal F.C.");
                jFotoTercer.setIcon(new ImageIcon("ArsenalNew.png"));
                break;
            case "2010-2011":
                tChamp.setText("Manchester United");
                tVez.setText("por duodécima vez en este formato");
                jFotoChamp.setIcon(new ImageIcon("ManU.png"));
                
                tSegundo.setText("Chelsea F.C.");
                jFotoSegundo.setIcon(new ImageIcon("ChelseaNew.png"));
                
                tTercer.setText("Manchester City");
                jFotoTercer.setIcon(new ImageIcon("ManCityOld.png"));
                break;
            case "2011-2012":
                tChamp.setText("Manchester City");
                tVez.setText("por primera vez en este formato");
                jFotoChamp.setIcon(new ImageIcon("ManCityOld.png"));
                
                tSegundo.setText("Manchester United");
                jFotoSegundo.setIcon(new ImageIcon("ManU.png"));
                
                tTercer.setText("Arsenal F.C.");
                jFotoTercer.setIcon(new ImageIcon("ArsenalNew.png"));
                break;
            case "2012-2013":
                tChamp.setText("Manchester United");
                tVez.setText("por decimotercera vez en este formato");
                jFotoChamp.setIcon(new ImageIcon("ManU.png"));
                
                tSegundo.setText("Manchester City");
                jFotoSegundo.setIcon(new ImageIcon("ManCityOld.png"));
                
                tTercer.setText("Chelsea F.C.");
                jFotoTercer.setIcon(new ImageIcon("ChelseaNew.png"));
                break;
            case "2013-2014":
                tChamp.setText("Manchester City");
                tVez.setText("por segunda vez en este formato");
                jFotoChamp.setIcon(new ImageIcon("ManCityOld.png"));
                
                tSegundo.setText("Liverpool F.C.");
                jFotoSegundo.setIcon(new ImageIcon("LFC.png"));
                
                tTercer.setText("Chelsea F.C.");
                jFotoTercer.setIcon(new ImageIcon("ChelseaNew.png"));
                break;
            case "2014-2015":
                tChamp.setText("Chelsea F.C.");
                tVez.setText("por cuarta vez en este formato");
                jFotoChamp.setIcon(new ImageIcon("ChelseaNew.png"));
                
                tSegundo.setText("Manchester City");
                jFotoSegundo.setIcon(new ImageIcon("ManCityOld.png"));
                
                tTercer.setText("Arsenal F.C.");
                jFotoTercer.setIcon(new ImageIcon("ArsenalNew.png"));
                break;
            case "2015-2016":
                tChamp.setText("Leicester City F.C.");
                tVez.setText("por primera vez en este formato");
                jFotoChamp.setIcon(new ImageIcon("LeicesterCity.png"));
                
                tSegundo.setText("Arsenal F.C.");
                jFotoSegundo.setIcon(new ImageIcon("ArsenalNew.png"));
                
                tTercer.setText("Tottenham Hotspur F.C.");
                jFotoTercer.setIcon(new ImageIcon("Spurs.png"));
                break;
            case "2016-2017":
                tChamp.setText("Chelsea F.C.");
                tVez.setText("por quinta vez en este formato");
                jFotoChamp.setIcon(new ImageIcon("ChelseaNew.png"));
                
                tSegundo.setText("Tottenham Hotspur F.C.");
                jFotoSegundo.setIcon(new ImageIcon("Spurs.png"));
                
                tTercer.setText("Manchester City");
                jFotoTercer.setIcon(new ImageIcon("ManCityNew.png"));
                break;
            case "2017-2018":
                tChamp.setText("Manchester City");
                tVez.setText("por tercera vez en este formato");
                jFotoChamp.setIcon(new ImageIcon("ManCityNew.png"));
                
                tSegundo.setText("Manchester United");
                jFotoSegundo.setIcon(new ImageIcon("ManU.png"));
                
                tTercer.setText("Tottenham Hotspur F.C.");
                jFotoTercer.setIcon(new ImageIcon("Spurs.png"));
                break;
            case "2018-2019":
                tChamp.setText("Manchester City");
                tVez.setText("por cuarta vez en este formato y segunda de forma consecutiva");
                jFotoChamp.setIcon(new ImageIcon("ManCityNew.png"));
                
                tSegundo.setText("Liverpool F.C.");
                jFotoSegundo.setIcon(new ImageIcon("LFC.png"));
                
                tTercer.setText("Chelsea F.C.");
                jFotoTercer.setIcon(new ImageIcon("ChelseaNew.png"));
                break;
            case "2019-2020":
                tChamp.setText("Liverpool F.C.");
                tVez.setText("por primera vez en este formato");
                jFotoChamp.setIcon(new ImageIcon("LFC.png"));
                
                tSegundo.setText("Manchester City");
                jFotoSegundo.setIcon(new ImageIcon("ManCityNew.png"));
                
                tTercer.setText("Manchester United");
                jFotoTercer.setIcon(new ImageIcon("ManU.png"));
                break;
        }
    }//GEN-LAST:event_anioActionPerformed

    private void LimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LimpiarActionPerformed
        // TODO add your handling code here:
        tChamp.setText("");
        tVez.setText("");
        tSegundo.setText("");
        tTercer.setText("");
        jFotoChamp.setVisible(false);
        jFotoSegundo.setVisible(false);
        jFotoTercer.setVisible(false);
    }//GEN-LAST:event_LimpiarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cover.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cover.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cover.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cover.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cover().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Limpiar;
    private javax.swing.JComboBox<String> anio;
    private javax.swing.JLabel jFotoChamp;
    private javax.swing.JLabel jFotoSegundo;
    private javax.swing.JLabel jFotoTercer;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField tChamp;
    private javax.swing.JTextField tSegundo;
    private javax.swing.JTextField tTercer;
    private javax.swing.JTextField tVez;
    // End of variables declaration//GEN-END:variables
}
